# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "capybara"
gem "rspec"
gem 'selenium-webdriver', '~> 4.19'
gem "ffi"
gem "cucumber"
gem 'webdrivers', '~> 5.0', require: false
